#!/bin/bash
short=false
if [ $# == 1 ]
then
    if [ $1 == short ]
    then
        short=true
    fi
fi
if [ ! -d data -a ! short ]
then
    mkdir data
    zipFiles=$(ls ${HOME}/KT/data/nsfAbstracts/*)
    for f in $zipFiles
    do
        unzip $f -d data/.
    done
fi
i=0
if [ short ]
then
    if [ ! -d bowFilesShort ]
    then
        mkdir bowFilesShort
    fi
    rm -rf moneyShort money
    xmlFiles=$(ls dataShort/*)
    for f in $xmlFiles
    do
        if [ $i == 5 ]
        then
            break
        fi
        newF=${f%.xml}
        newF=${newF#dataShort}
        if [ ! -d bowFilesShort/${newF:0:3} ]
        then
            mkdir bowFilesShort/${newF:0:3}
        fi
        parsePy $f > bowFilesShort/${newF:0:3}/$newF
        eval i=$i+1
    done
    mv money moneyShort
else
    if [ ! -d bowFiles ]
    then
        mkdir bowFiles
    fi
    rm money
    xmlFiles=$(ls data/*)
    for f in $xmlFiles
    do
        if [ $i == 5 ]
        then
            break
        fi
        newF=${f%.xml}
        newF=${newF#data}
        if [ ! -d bowFiles/${newF:0:3} ]
        then
            mkdir bowFiles/${newF:0:3}
        fi
        parsePy $f > bowFiles/${newF:0:3}/$newF
        eval i=$i+1
    done
fi

if [ short ]
then
    rainbow -d ./model --index bowFilesShort/*
    rainbow -d ./model --print-matrix > bowMatrix
    bowToMtxPy
else
    rainbow -d ./model --index bowFiles/*
    rainbow -d ./model --print-matrix > bowMatrix
    bowToMtxPy
fi
